package com.tests.mobileCIF;

import java.util.Map;

import org.testng.annotations.BeforeClass;
import org.testng.annotations.Optional;
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.markuputils.ExtentColor;
import com.aventstack.extentreports.markuputils.MarkupHelper;
import com.aventstack.extentreports.service.ExtentTestManager;
import com.controls.ObjectsControl;
import com.github.javafaker.Faker;
import com.pages.desktopCIF.DesktopCIFLoginPage;
import com.pages.desktopCIF.OtherPage;
import com.pages.desktopCIF.ParentAndGuardianPage;
import com.pages.desktopCIF.ProspectiveStudentPage;
import com.pages.desktopRegistrationLegacyForm.DesktopRegistrationLegacyFormPage;
import com.pages.embedCode.EmbedCodeLoginPage;
import com.pages.mobileCIF.MobileCifPage;
import com.tests.BaseTest;

public class MobileCifTest extends BaseTest{
	String url;
	MobileCifPage mobileCifLogin = null;
	DesktopCIFLoginPage cifLogin = null;
	OtherPage otherPage = null;
	ParentAndGuardianPage mobileParentAndGuardianPage = null;
	EmbedCodeLoginPage loginPage = null;
	ProspectiveStudentPage mobileProspectiveStudentPage = null;
	ObjectsControl objectControl = null;
	Faker faker = new Faker();
	String firstName = faker.name().firstName();
	String lastName = faker.name().lastName();
	String emailID = faker.name().firstName();
	DesktopRegistrationLegacyFormPage mobileRegistrationLegacyFormPage = null;

	@BeforeClass
	public void classSetUp() throws Exception{
		url = prop.getProperty("staging_env")+prop.getProperty("url_cif");
		mobileCifLogin = new MobileCifPage(remoteDriver);
		cifLogin = new DesktopCIFLoginPage(remoteDriver);
		otherPage = new OtherPage(remoteDriver);
		mobileParentAndGuardianPage = new ParentAndGuardianPage(remoteDriver);
		loginPage = new EmbedCodeLoginPage(remoteDriver);
		mobileProspectiveStudentPage = new ProspectiveStudentPage(remoteDriver);
		objectControl = new ObjectsControl(remoteDriver);
		mobileRegistrationLegacyFormPage = new DesktopRegistrationLegacyFormPage(remoteDriver);
	}

	@Test   
	@Parameters({"browser"})
	public void C16434_C16435_WelcomePageVisitorType(@Optional("IamOptional")String browser) throws Exception{
		System.err.println("MobileCIF_C16434_C16435_WelcomePageVisitorType ["+browserName+"]");
		//		ExtentTestManager.getTest().info(MarkupHelper.createLabel("C16434_C16435_WelcomePageVisitorType", ExtentColor.BLUE));
		ExtentTestManager.getTest().assignAuthor(browserName);
		ExtentTestManager.getTest().assignCategory(browserName);
		ExtentTestManager.getTest().generateLog(Status.INFO, "MobileCIF_C16434_C16435_WelcomePageVisitorType ["+browserName+"]");
		ExtentTestManager.getTest().info(MarkupHelper.createLabel("MobileCIF_C16434_C16435_WelcomePageVisitorType ["+browserName+"]", ExtentColor.RED));

		mobileCifLogin.navigateToMobileCIFLogin(url);
		ExtentTestManager.getTest().pass("Login to application with Mobile CIF url");
		mobileCifLogin.switchToTheVirtualtourFrame();
		otherPage.verifyWelcomeStonybrookHeader();
		ExtentTestManager.getTest().pass("WelcomeStonybrookHeader is verified");
		cifLogin.verifyAreYouLabel();
		ExtentTestManager.getTest().pass("AreYouLabel is verified");
		cifLogin.verifyProspectiveStudentButton();
		ExtentTestManager.getTest().pass("Prospective Student button label displayed on the Registration page");
		cifLogin.verifyParentGuardianButton();
		ExtentTestManager.getTest().pass("Parent/Guardian button label displayed on the Registration page");
		cifLogin.verifyOtherButton();
		ExtentTestManager.getTest().pass("Other button label displayed on the Registration page");
		mobileCifLogin.verifyTermsOfUseLink();
		ExtentTestManager.getTest().pass("TermsOfUseLink is displayed on the Registration page");
		mobileCifLogin.verifyPrivacyPolicyLink();
		ExtentTestManager.getTest().pass("PrivacyPolicyLink is displayed on the Registration page");
	}

	@Test   
	@Parameters({"browser"})  
	public void C66272_VerifyThatCIFIsAbortedIfUserIsInCAAndHasGPCEnabled(@Optional("IamOptional")String browser) throws Exception{
		System.err.println("MobileCIF_C66272_VerifyThatCIFIsAbortedIfUserIsInCAAndHasGPCEnabled ["+browserName+"]");
		//		ExtentTestManager.getTest().info(MarkupHelper.createLabel("C66272_VerifyThatCIFIsAbortedIfUserIsInCAAndHasGPCEnabled", ExtentColor.BLUE));
		ExtentTestManager.getTest().assignAuthor(browserName);
		ExtentTestManager.getTest().assignCategory(browserName);
		ExtentTestManager.getTest().generateLog(Status.INFO, "MobileCIF_C66272_VerifyThatCIFIsAbortedIfUserIsInCAAndHasGPCEnabled ["+browserName+"]");
		ExtentTestManager.getTest().info(MarkupHelper.createLabel("MobileCIF_C66272_VerifyThatCIFIsAbortedIfUserIsInCAAndHasGPCEnabled ["+browserName+"]", ExtentColor.RED));

		Map<String, String> setData = otherPage.setData();
		mobileCifLogin.navigateToMobileCIFLogin(url);
		ExtentTestManager.getTest().pass("Login to application with Mobile CIF url");
		mobileCifLogin.switchToTheVirtualtourFrame();
		otherPage.verifyWelcomeStonybrookHeader();
		ExtentTestManager.getTest().pass("WelcomeStonybrookHeader is verified");
		cifLogin.verifyAreYouLabel();
		ExtentTestManager.getTest().pass("AreYouLabel is verified");
		cifLogin.clickProspectiveStudentButton();
		ExtentTestManager.getTest().pass("prospective_student is clicked");
		mobileProspectiveStudentPage.ClickProspectiveStudentCollegeStudentButton();
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		otherPage.enterEmail(setData.get("EmailID"));
		ExtentTestManager.getTest().pass("Enter the email");
		otherPage.enterFirstName(setData.get("FirstName"));
		ExtentTestManager.getTest().pass("Enter the firstname");
		otherPage.enterLastName(setData.get("LastName"));
		ExtentTestManager.getTest().pass("Enter the lastname");
		mobileCifLogin.enterDOBUnder16();
		ExtentTestManager.getTest().pass("Enter the dob as below 16 yrs.");
		mobileCifLogin.jsClickNextButton();
		mobileProspectiveStudentPage.verifyThanksMessageForUnder16DOB();
		ExtentTestManager.getTest().pass("ThanksMessage For Under16 DOB is verified");
	}

	@Test   
	@Parameters({"browser"})
	public void C16443_ClosedButton(@Optional("IamOptional")String browser) throws Exception	{
		System.err.println("C16443_ClosedButton ["+browserName+"]");
		//		ExtentTestManager.getTest().assignCategory("C16443_ClosedButton");
		ExtentTestManager.getTest().assignAuthor(browserName);
		ExtentTestManager.getTest().assignCategory(browserName);
		ExtentTestManager.getTest().generateLog(Status.INFO, "C16443_ClosedButton ["+browserName+"]");
		ExtentTestManager.getTest().info(MarkupHelper.createLabel("C16443_ClosedButton ["+browserName+"]", ExtentColor.RED));

		Map<String, String> setData = otherPage.setData();
		mobileCifLogin.navigateToMobileCIFLogin(url);
		ExtentTestManager.getTest().pass("Login to application with Mobile CIF url");
		mobileCifLogin.switchToTheVirtualtourFrame();
		otherPage.verifyWelcomeStonybrookHeader();
		cifLogin.verifyAreYouLabel();
		cifLogin.clickProspectiveStudentButton();
		ExtentTestManager.getTest().pass("prospective_student is clicked");
		mobileProspectiveStudentPage.switchToTheDefaultContent();
		mobileProspectiveStudentPage.clickCloseButton();
		ExtentTestManager.getTest().pass("Click Close_Registration Button");
		mobileProspectiveStudentPage.clickBookLink();
		ExtentTestManager.getTest().pass("Click on BookLinkLink");
		mobileCifLogin.clickRegisterButton();
		ExtentTestManager.getTest().pass("Click on Register button");
		mobileCifLogin.switchToTheVirtualtourFrame();
		mobileProspectiveStudentPage.clickProspectiveStudentHighSchoolStudentButton();
		ExtentTestManager.getTest().pass("ProspectiveStudentHighSchoolStudentButton is clicked");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileProspectiveStudentPage.switchToTheDefaultContent();
		mobileProspectiveStudentPage.clickCloseButton();
		ExtentTestManager.getTest().pass("Click Close_Registration Button");
		mobileCifLogin.clickRegisterButton();
		ExtentTestManager.getTest().pass("Click on Register button");
		mobileCifLogin.switchToTheVirtualtourFrame();
		otherPage.enterEmail(setData.get("EmailID"));
		ExtentTestManager.getTest().pass("Enter the email");
		otherPage.enterFirstName(setData.get("FirstName"));
		ExtentTestManager.getTest().pass("Enter the firstname");
		otherPage.enterLastName(setData.get("LastName"));
		ExtentTestManager.getTest().pass("Enter the lastname");
		mobileCifLogin.enterDOB(setData.get("DoB"));
		ExtentTestManager.getTest().pass("Enter the dob");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileProspectiveStudentPage.switchToTheDefaultContent();
		mobileProspectiveStudentPage.clickCloseButton();
		ExtentTestManager.getTest().pass("Click Close_Registration Button");
		mobileCifLogin.clickRegisterButton();
		ExtentTestManager.getTest().pass("Click on Register button");
		mobileCifLogin.switchToTheVirtualtourFrame();
		mobileCifLogin.enterPostalCode(setData.get("PostalCode"));
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileProspectiveStudentPage.switchToTheDefaultContent();
		mobileProspectiveStudentPage.clickCloseButton();
		ExtentTestManager.getTest().pass("Click Close_Registration Button");
		mobileCifLogin.clickRegisterButton();
		ExtentTestManager.getTest().pass("Click on Register button");
		mobileCifLogin.switchToTheVirtualtourFrame();
		mobileProspectiveStudentPage.enterCurrentHighSchoolName();
		ExtentTestManager.getTest().pass("CurrentHighSchoolName is entered");
		otherPage.clickNextButton();
		mobileProspectiveStudentPage.clickIntendedMajorDropdown();
		mobileProspectiveStudentPage.enterIntendedMajorDropdown("Anthropology");
		ExtentTestManager.getTest().pass("IndendedMajorDropdown is entered");
		otherPage.clickNextButton();
		mobileRegistrationLegacyFormPage.selectSATScore();
		ExtentTestManager.getTest().pass("SatScore is entered");
		mobileRegistrationLegacyFormPage.selectACTScore();
		ExtentTestManager.getTest().pass("ActScore is entered");
		mobileRegistrationLegacyFormPage.selectGPAScore(setData.get("GpaScore"));
		ExtentTestManager.getTest().pass("GpaScore is entered");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileParentAndGuardianPage.enterPhoneNumber(setData.get("PhoneNo"));
		ExtentTestManager.getTest().pass("PhoneNumber is entered");
		mobileRegistrationLegacyFormPage.selectGenderDropdownOptionDynamic();
		ExtentTestManager.getTest().pass("Gender is selected");
		mobileCifLogin.clickAcknowledgementCheckbox();
		ExtentTestManager.getTest().pass("AcknowledgementCheckbox is clicked");
		otherPage.clickDoneButton();
		ExtentTestManager.getTest().pass("Done button is clicked");
		otherPage.verifyGetReadyMessage();
		ExtentTestManager.getTest().pass("Get ready message is verified");
		mobileCifLogin.verifyLearnButtonLinkAfterCompleteTheRegister();
		ExtentTestManager.getTest().pass("Learn More Link is verified");
	}

	@Test   
	@Parameters({"browser"})  
	public void C16442_OptionalFields(@Optional("IamOptional")String browser) throws Exception{
		System.err.println("CIFMobile_C16442_OptionalFields ["+browserName+"]");
		//		ExtentTestManager.getTest().info(MarkupHelper.createLabel("C16442_OptionalFields", ExtentColor.BLUE));
		ExtentTestManager.getTest().assignAuthor(browserName);
		ExtentTestManager.getTest().assignCategory(browserName);
		ExtentTestManager.getTest().generateLog(Status.INFO, "CIFMobile_C16442_OptionalFields ["+browserName+"]");
		ExtentTestManager.getTest().info(MarkupHelper.createLabel("CIFMobile_C16442_OptionalFields ["+browserName+"]", ExtentColor.RED));

		Map<String, String> setData = otherPage.setData();
		mobileCifLogin.navigateToMobileCIFLogin(url);
		ExtentTestManager.getTest().pass("Login to application with Mobile CIF url");
		mobileCifLogin.switchToTheVirtualtourFrame();
		otherPage.verifyWelcomeStonybrookHeader();
		cifLogin.verifyAreYouLabel();
		cifLogin.clickProspectiveStudentButton();
		ExtentTestManager.getTest().pass("prospective_student is clicked");
		mobileProspectiveStudentPage.ClickProspectiveStudentCollegeStudentButton();
		otherPage.clickNextButton();
		otherPage.enterEmail(setData.get("EmailID"));
		ExtentTestManager.getTest().pass("Enter the email");
		otherPage.enterFirstName(setData.get("FirstName"));
		ExtentTestManager.getTest().pass("Enter the firstname");
		otherPage.enterLastName(setData.get("LastName"));
		ExtentTestManager.getTest().pass("Enter the lastname");
		mobileCifLogin.enterDOB(setData.get("DoB"));
		ExtentTestManager.getTest().pass("Enter the dob");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.enterPostalCode(setData.get("PostalCode"));
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.enterPhoneNumber(setData.get("PhoneNo"));
		mobileRegistrationLegacyFormPage.selectGenderDropdownOptionDynamic();
		ExtentTestManager.getTest().pass("Gender is selected");
		mobileCifLogin.clickAcknowledgementCheckbox();
		ExtentTestManager.getTest().pass("Acknowledgement Checkbox is clicked");
		otherPage.clickDoneButton();
		otherPage.verifyGetReadyMessage();
		ExtentTestManager.getTest().pass("Get ready message is verified");
	}

	@Test   
	@Parameters({"browser"})  
	public void C16439_ScorePage(@Optional("IamOptional")String browser) throws Exception {
		System.err.println("MobileCIF - C16439_ScorePage ["+browserName+"]");
		//		ExtentTestManager.getTest().info(MarkupHelper.createLabel("C16439_ScorePage", ExtentColor.BLUE));
		ExtentTestManager.getTest().assignAuthor(browserName);
		ExtentTestManager.getTest().assignCategory(browserName);
		ExtentTestManager.getTest().generateLog(Status.INFO, "MobileCIF - C16439_ScorePage ["+browserName+"]");
		ExtentTestManager.getTest().info(MarkupHelper.createLabel("MobileCIF - C16439_ScorePage ["+browserName+"]", ExtentColor.RED));

		Map<String, String> setData = otherPage.setData();
		mobileCifLogin.navigateToMobileCIFLogin(url);
		ExtentTestManager.getTest().pass("Login to application with Mobile CIF url");
		mobileCifLogin.switchToTheVirtualtourFrame();
		otherPage.verifyWelcomeStonybrookHeader();
		cifLogin.verifyAreYouLabel();
		cifLogin.clickProspectiveStudentButton();
		ExtentTestManager.getTest().pass("prospective_student is clicked");
		mobileProspectiveStudentPage.clickProspectiveStudentHighSchoolStudentButton();
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		otherPage.enterEmail(setData.get("EmailID"));
		ExtentTestManager.getTest().pass("Enter the email");
		otherPage.enterFirstName(setData.get("FirstName"));
		ExtentTestManager.getTest().pass("Enter the firstname");
		otherPage.enterLastName(setData.get("LastName"));
		ExtentTestManager.getTest().pass("Enter the lastname");
		mobileCifLogin.enterDOB(setData.get("DoB"));
		ExtentTestManager.getTest().pass("Enter the dob");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.enterPostalCode(setData.get("PostalCode"));
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileProspectiveStudentPage.enterCurrentHighSchoolName();
		ExtentTestManager.getTest().pass("CurrentHighSchoolName is entered");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileProspectiveStudentPage.clickIntendedMajorDropdown();
		mobileProspectiveStudentPage.enterIntendedMajorDropdown("Anthropology");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.enterInvalidSatScoreAndVerifyTheErrorMessage();
		mobileRegistrationLegacyFormPage.selectSATScore();
		mobileCifLogin.enterInvalidActScoreAndVerifyTheErrorMessage();
		mobileCifLogin.enterActScoreTextbox();
		mobileCifLogin.enterInvalidGpacoreAndVerifyTheErrorMessage();
		mobileRegistrationLegacyFormPage.selectGPAScore(setData.get("GpaScore"));
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.enterPhoneNumber(setData.get("PhoneNo"));
		mobileRegistrationLegacyFormPage.selectGenderDropdownOptionDynamic();
		ExtentTestManager.getTest().pass("Gender is selected");
		mobileCifLogin.clickAcknowledgementCheckbox();
		ExtentTestManager.getTest().pass("AcknowledgementCheckbox is clicked");
		otherPage.clickDoneButton();
		ExtentTestManager.getTest().pass("Done button is clicked");
		otherPage.verifyGetReadyMessage();
		ExtentTestManager.getTest().pass("Get ready message is verified");
	}

	@Test   
	@Parameters({"browser"})  
	public void C16437_WhoTheyIntendToBe(@Optional("IamOptional")String browser) throws Exception{
		System.err.println("MobileCIF - C16437_WhoTheyIntendToBe ["+browserName+"]");
		//		ExtentTestManager.getTest().info(MarkupHelper.createLabel("C16437_WhoTheyIntendToBe", ExtentColor.BLUE));
		ExtentTestManager.getTest().assignAuthor(browserName);
		ExtentTestManager.getTest().assignCategory(browserName);
		ExtentTestManager.getTest().generateLog(Status.INFO, "MobileCIF - C16437_WhoTheyIntendToBe ["+browserName+"]");
		ExtentTestManager.getTest().info(MarkupHelper.createLabel("MobileCIF - C16437_WhoTheyIntendToBe ["+browserName+"]", ExtentColor.RED));

		Map<String, String> setData = otherPage.setData();
		mobileCifLogin.navigateToMobileCIFLogin(url);
		ExtentTestManager.getTest().pass("Login to application with Mobile CIF url");
		mobileCifLogin.switchToTheVirtualtourFrame();
		otherPage.verifyWelcomeStonybrookHeader();
		cifLogin.verifyAreYouLabel();
		cifLogin.clickProspectiveStudentButton();
		ExtentTestManager.getTest().pass("prospective_student is clicked");
		mobileProspectiveStudentPage.clickProspectiveStudentHighSchoolStudentButton();
		ExtentTestManager.getTest().pass("ProspectiveStudentHighSchoolStudentButton is clicked");
		mobileProspectiveStudentPage.verifyHighSchoolGraduationYearLabel();
		mobileProspectiveStudentPage.verifyHighSchoolIntendedEnrollmentYearTermLabel();
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		otherPage.enterEmail(setData.get("EmailID"));
		ExtentTestManager.getTest().pass("Enter the email");
		otherPage.enterFirstName(setData.get("FirstName"));
		ExtentTestManager.getTest().pass("Enter the firstname");
		otherPage.enterLastName(setData.get("LastName"));
		ExtentTestManager.getTest().pass("Enter the lastname");
		mobileCifLogin.enterDOB(setData.get("DoB"));
		ExtentTestManager.getTest().pass("Enter the dob");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.enterPostalCode(setData.get("PostalCode"));
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileProspectiveStudentPage.enterCurrentHighSchoolName();
		ExtentTestManager.getTest().pass("CurrentHighSchoolName is entered");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileProspectiveStudentPage.clickIntendedMajorDropdown();
		mobileProspectiveStudentPage.enterIntendedMajorDropdown("Anthropology");
		ExtentTestManager.getTest().pass("IndendedMajorDropdown is entered");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileRegistrationLegacyFormPage.selectSATScore();
		ExtentTestManager.getTest().pass("SAT score is entered");
		mobileRegistrationLegacyFormPage.selectACTScore();
		ExtentTestManager.getTest().pass("ACT score is entered");
		mobileRegistrationLegacyFormPage.selectGPAScore(setData.get("GpaScore"));
		ExtentTestManager.getTest().pass("GPA score is entered");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.enterPhoneNumber(setData.get("PhoneNo"));
		mobileRegistrationLegacyFormPage.selectGenderDropdownOptionDynamic();
		ExtentTestManager.getTest().pass("Gender is selected");
		mobileCifLogin.clickAcknowledgementCheckbox();
		ExtentTestManager.getTest().pass("AcknowledgementCheckbox is clicked");
		otherPage.clickDoneButton();
		ExtentTestManager.getTest().pass("Done button is clicked");
		otherPage.verifyGetReadyMessage();
		ExtentTestManager.getTest().pass("Get ready message is verified");
	}

	@Test   
	@Parameters({"browser"})  
	public void C16440_DemographicPage(@Optional("IamOptional")String browser) throws Exception{
		System.err.println("MobileCIF - C16440_DemographicPage ["+browserName+"]");
		//		ExtentTestManager.getTest().info(MarkupHelper.createLabel("C16440_DemographicPage", ExtentColor.BLUE));
		ExtentTestManager.getTest().assignAuthor(browserName);
		ExtentTestManager.getTest().assignCategory(browserName);
		ExtentTestManager.getTest().generateLog(Status.INFO, "MobileCIF - C16440_DemographicPage ["+browserName+"]");
		ExtentTestManager.getTest().info(MarkupHelper.createLabel("MobileCIF - C16440_DemographicPage ["+browserName+"]", ExtentColor.RED));

		Map<String, String> setData = otherPage.setData();
		mobileCifLogin.navigateToMobileCIFLogin(url);
		ExtentTestManager.getTest().pass("Login to application with Mobile CIF url");
		mobileCifLogin.switchToTheVirtualtourFrame();
		otherPage.verifyWelcomeStonybrookHeader();
		cifLogin.verifyAreYouLabel();
		cifLogin.clickProspectiveStudentButton();
		ExtentTestManager.getTest().pass("prospective_student is clicked");
		mobileProspectiveStudentPage.clickProspectiveStudentHighSchoolStudentButton();
		ExtentTestManager.getTest().pass("ProspectiveStudentHighSchoolStudentButton is clicked");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		otherPage.enterEmail(setData.get("EmailID"));
		ExtentTestManager.getTest().pass("Enter the email");
		otherPage.enterFirstName(setData.get("FirstName"));
		ExtentTestManager.getTest().pass("Enter the firstname");
		otherPage.enterLastName(setData.get("LastName"));
		ExtentTestManager.getTest().pass("Enter the lastname");
		mobileCifLogin.enterDOB(setData.get("DoB"));
		ExtentTestManager.getTest().pass("Enter the dob");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		ExtentTestManager.getTest().pass("Click next without enter postal code");
		otherPage.clickNextButton();
		mobileProspectiveStudentPage.verifyEnterValidPostalCodeAlertMessage();
		ExtentTestManager.getTest().pass("Enter Valid Postal Code Alert Message is verified");
		mobileCifLogin.enterPostalCode("9");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Enter invalid postal code and click next button");
		mobileProspectiveStudentPage.verifyEnterValidPostalCodeAlertMessage();
		ExtentTestManager.getTest().pass("Enter Valid Postal Code Alert Message is verified");
		mobileCifLogin.enterPostalCode("9@");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Enter invalid postal code and click next button");
		mobileProspectiveStudentPage.verifyEnterValidPostalCodeAlertMessage();
		ExtentTestManager.getTest().pass("Enter Valid Postal Code Alert Message is verified");
		mobileCifLogin.enterPostalCode("H1H1H1");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Enter invalid postal code and click next button");
		mobileProspectiveStudentPage.verifyEnterValidPostalCodeAlertMessage();
		ExtentTestManager.getTest().pass("Enter Valid Postal Code Alert Message is verified");
		mobileCifLogin.enterPostalCode(setData.get("PostalCode"));
		otherPage.clickNextButton();
		mobileProspectiveStudentPage.enterCurrentHighSchoolName();
		ExtentTestManager.getTest().pass("CurrentHighSchoolName is entered");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileProspectiveStudentPage.clickIntendedMajorDropdown();
		mobileProspectiveStudentPage.enterIntendedMajorDropdown("Anthropology");
		ExtentTestManager.getTest().pass("IndendedMajorDropdown is entered");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileRegistrationLegacyFormPage.selectSATScore();
		ExtentTestManager.getTest().pass("SAT score is entered");
		mobileRegistrationLegacyFormPage.selectACTScore();
		ExtentTestManager.getTest().pass("ACT score is entered");
		mobileRegistrationLegacyFormPage.selectGPAScore(setData.get("GpaScore"));
		ExtentTestManager.getTest().pass("GPA score is entered");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.enterPhoneNumber(setData.get("PhoneNo"));
		mobileRegistrationLegacyFormPage.selectGenderDropdownOptionDynamic();
		ExtentTestManager.getTest().pass("Gender is selected");
		mobileCifLogin.clickAcknowledgementCheckbox();
		ExtentTestManager.getTest().pass("AcknowledgementCheckbox is clicked");
		otherPage.clickDoneButton();
		ExtentTestManager.getTest().pass("Done button is clicked");
		otherPage.verifyGetReadyMessage();
		ExtentTestManager.getTest().pass("Get ready message is verified");
	}

	@Test   
	@Parameters({"browser"})  
	public void C16441_AdditionalInfoPage(@Optional("IamOptional")String browser) throws Exception{
		System.err.println("MobileCIF - C16441_AdditionalInfoPage ["+browserName+"]");
		//		ExtentTestManager.getTest().info(MarkupHelper.createLabel("C16441_AdditionalInfoPage", ExtentColor.BLUE));
		ExtentTestManager.getTest().assignAuthor(browserName);
		ExtentTestManager.getTest().assignCategory(browserName);
		ExtentTestManager.getTest().generateLog(Status.INFO, "MobileCIF - C16441_AdditionalInfoPage ["+browserName+"]");
		ExtentTestManager.getTest().info(MarkupHelper.createLabel("MobileCIF - C16441_AdditionalInfoPage ["+browserName+"]", ExtentColor.RED));

		Map<String, String> setData = otherPage.setData();
		mobileCifLogin.navigateToMobileCIFLogin(url);
		ExtentTestManager.getTest().pass("Login to application with Mobile CIF url");
		mobileCifLogin.switchToTheVirtualtourFrame();
		otherPage.verifyWelcomeStonybrookHeader();
		cifLogin.verifyAreYouLabel();
		cifLogin.clickProspectiveStudentButton();
		ExtentTestManager.getTest().pass("prospective_student is clicked");
		mobileProspectiveStudentPage.clickProspectiveStudentHighSchoolStudentButton();
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		otherPage.enterEmail(setData.get("EmailID"));
		ExtentTestManager.getTest().pass("Enter the email");
		otherPage.enterFirstName(setData.get("FirstName"));
		ExtentTestManager.getTest().pass("Enter the firstname");
		otherPage.enterLastName(setData.get("LastName"));
		ExtentTestManager.getTest().pass("Enter the lastname");
		mobileCifLogin.enterDOB(setData.get("DoB"));
		ExtentTestManager.getTest().pass("Enter the dob");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.enterPostalCode(setData.get("PostalCode"));
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileProspectiveStudentPage.enterCurrentHighSchoolName();
		ExtentTestManager.getTest().pass("CurrentHighSchoolName is entered");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileProspectiveStudentPage.clickIntendedMajorDropdown();
		mobileProspectiveStudentPage.enterIntendedMajorDropdown("Anthropology");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileRegistrationLegacyFormPage.selectSATScore();
		mobileRegistrationLegacyFormPage.selectACTScore();
		mobileRegistrationLegacyFormPage.selectGPAScore(setData.get("GpaScore"));
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.enterPhoneNumber(setData.get("PhoneNo"));
		mobileRegistrationLegacyFormPage.selectGenderDropdownOptionDynamic();
		ExtentTestManager.getTest().pass("Gender is selected");
		mobileCifLogin.clickAcknowledgementCheckbox();
		ExtentTestManager.getTest().pass("AcknowledgementCheckbox is clicked");
		otherPage.clickDoneButton();
		ExtentTestManager.getTest().pass("Done button is clicked");
		otherPage.verifyGetReadyMessage();
		ExtentTestManager.getTest().pass("Get ready message is verified");
	}

	@Test   
	@Parameters({"browser"})  
	public void C16438_VerifyNameInformationPage(@Optional("IamOptional")String browser) throws Exception{
		System.err.println("MobileCIF - C16438_VerifyNameInformationPage ["+browserName+"]");
		//		ExtentTestManager.getTest().info(MarkupHelper.createLabel("C16438_VerifyNameInformationPage", ExtentColor.BLUE));
		ExtentTestManager.getTest().assignAuthor(browserName);
		ExtentTestManager.getTest().assignCategory(browserName);
		ExtentTestManager.getTest().generateLog(Status.INFO, "MobileCIF - C16438_VerifyNameInformationPage ["+browserName+"]");
		ExtentTestManager.getTest().info(MarkupHelper.createLabel("MobileCIF - C16438_VerifyNameInformationPage ["+browserName+"]", ExtentColor.RED));

		mobileCifLogin.navigateToMobileCIFLogin(url);
		ExtentTestManager.getTest().pass("Login to application with Mobile CIF url");
		mobileCifLogin.switchToTheVirtualtourFrame();
		otherPage.verifyWelcomeStonybrookHeader();
		cifLogin.verifyAreYouLabel();
		cifLogin.clickProspectiveStudentButton();
		ExtentTestManager.getTest().pass("prospective_student is clicked");
		mobileProspectiveStudentPage.clickProspectiveStudentHighSchoolStudentButton();
		mobileProspectiveStudentPage.verifyHighSchoolGraduationYearLabel();
		ExtentTestManager.getTest().pass("High School Graduation Year label appears");
		mobileProspectiveStudentPage.verifyHighSchoolIntendedEnrollmentYearTermLabel();
		ExtentTestManager.getTest().pass("High School INTENDED ENROLLMENT YEAR & TERM label appears");
		otherPage.clickNextButton();	
		ExtentTestManager.getTest().pass("Next button clicked on High School Graduation page");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button clicked without filling any value on Name & DOB page page");
		mobileProspectiveStudentPage.verifyPleaseEnterValidFirstNameErrorMessage();
		ExtentTestManager.getTest().pass("PleaseEnterValidFirstNameErrorMessage is verified");
		mobileProspectiveStudentPage.verifyPleaseEnterValidLastNameErrorMessage();
		ExtentTestManager.getTest().pass("PleaseEnterValidLastNameErrorMessage is verified");
		mobileProspectiveStudentPage.verifyPleaseEnterValidEmailIDErrorMessage();
		ExtentTestManager.getTest().pass("PleaseEnterValidEmailIDErrorMessage is verified");
		mobileProspectiveStudentPage.verifyPleaseEnterValidDOBErrorMessage();
		ExtentTestManager.getTest().pass("PleaseEnterValidDOBErrorMessage is verified");
	}

	@Test   
	@Parameters({"browser"})
	public void C16445_VerifyTheUserCanRegisterAsProspectiveStudentHighSchoolStudentEmail(@Optional("IamOptional")String browser) throws Exception{
		System.err.println("MobileCIF - C16445_VerifyTheUserCanRegisterAsProspectiveStudent_HighSchoolStudent_Email ["+browserName+"]");
		//		ExtentTestManager.getTest().info(MarkupHelper.createLabel("C16445_VerifyTheUserCanRegisterAsProspectiveStudent_HighSchoolStudent_Email", ExtentColor.BLUE));
		ExtentTestManager.getTest().assignAuthor(browserName);
		ExtentTestManager.getTest().assignCategory(browserName);
		ExtentTestManager.getTest().generateLog(Status.INFO, "MobileCIF - C16445_VerifyTheUserCanRegisterAsProspectiveStudent_HighSchoolStudent_Email ["+browserName+"]");
		ExtentTestManager.getTest().info(MarkupHelper.createLabel("MobileCIF - C16445_VerifyTheUserCanRegisterAsProspectiveStudent_HighSchoolStudent_Email", ExtentColor.RED));

		Map<String, String> setData = otherPage.setData();
		mobileCifLogin.navigateToMobileCIFLogin(url);
		ExtentTestManager.getTest().pass("Login to application with Mobile CIF url");
		mobileCifLogin.switchToTheVirtualtourFrame();
		otherPage.verifyWelcomeStonybrookHeader();
		cifLogin.verifyAreYouLabel();
		cifLogin.clickProspectiveStudentButton();
		ExtentTestManager.getTest().pass("prospective_student is clicked");
		mobileProspectiveStudentPage.clickProspectiveStudentHighSchoolStudentButton();
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		otherPage.enterFirstName(setData.get("FirstName"));
		ExtentTestManager.getTest().pass("Enter the firstname");
		otherPage.enterLastName(setData.get("LastName"));
		ExtentTestManager.getTest().pass("Enter the lastname");
		mobileCifLogin.enterDOB(setData.get("DoB"));
		ExtentTestManager.getTest().pass("Enter the dob");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button clicked without filling any value on Email field");	
		mobileProspectiveStudentPage.verifyPleaseEnterValidEmailIDErrorMessage();
		ExtentTestManager.getTest().pass("PleaseEnterValidEmailIDErrorMessage is verified");	
		otherPage.enterEmail(setData.get("EmailID"));
		ExtentTestManager.getTest().pass("Enter the email");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.enterPostalCode(setData.get("PostalCode"));
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileProspectiveStudentPage.enterCurrentHighSchoolName();
		ExtentTestManager.getTest().pass("CurrentHighSchoolName is entered");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileProspectiveStudentPage.clickIntendedMajorDropdown();
		mobileProspectiveStudentPage.enterIntendedMajorDropdown("Anthropology");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileRegistrationLegacyFormPage.selectSATScore();
		mobileRegistrationLegacyFormPage.selectACTScore();
		mobileRegistrationLegacyFormPage.selectGPAScore(setData.get("GpaScore"));
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.enterPhoneNumber(setData.get("PhoneNo"));
		mobileRegistrationLegacyFormPage.selectGenderDropdownOptionDynamic();
		ExtentTestManager.getTest().pass("Gender is selected");
		mobileCifLogin.clickAcknowledgementCheckbox();
		ExtentTestManager.getTest().pass("AcknowledgementCheckbox is clicked");
		otherPage.clickDoneButton();
		ExtentTestManager.getTest().pass("Done button is clicked");
		otherPage.verifyGetReadyMessage();
		ExtentTestManager.getTest().pass("Get ready message is verified");
	}

	@Test   
	@Parameters({"browser"})
	public void C16446_VerifyVerifyTheUserCanRegisterAsProspectiveStudentHighSchoolStudentName(@Optional("IamOptional")String browser) throws Exception{
		System.err.println("MobileCIF - C16446_VerifyVerifyTheUserCanRegisterAsProspectiveStudent_HighSchoolStudent_Name ["+browserName+"]");
		//		ExtentTestManager.getTest().info(MarkupHelper.createLabel("C16446_VerifyVerifyTheUserCanRegisterAsProspectiveStudent_HighSchoolStudent_Name", ExtentColor.BLUE));
		ExtentTestManager.getTest().assignAuthor(browserName);
		ExtentTestManager.getTest().assignCategory(browserName);
		ExtentTestManager.getTest().generateLog(Status.INFO, "MobileCIF - C16446_VerifyVerifyTheUserCanRegisterAsProspectiveStudent_HighSchoolStudent_Name ["+browserName+"]");
		ExtentTestManager.getTest().info(MarkupHelper.createLabel("MobileCIF - C16446_VerifyVerifyTheUserCanRegisterAsProspectiveStudent_HighSchoolStudent_Name ["+browserName+"]", ExtentColor.RED));

		Map<String, String> setData = otherPage.setData();
		mobileCifLogin.navigateToMobileCIFLogin(url);
		ExtentTestManager.getTest().pass("Login to application with Mobile CIF url");
		mobileCifLogin.switchToTheVirtualtourFrame();
		otherPage.verifyWelcomeStonybrookHeader();
		cifLogin.verifyAreYouLabel();
		cifLogin.clickProspectiveStudentButton();
		ExtentTestManager.getTest().pass("prospective_student is clicked");
		mobileProspectiveStudentPage.clickProspectiveStudentHighSchoolStudentButton();
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		otherPage.enterEmail(setData.get("EmailID"));
		ExtentTestManager.getTest().pass("Enter the email");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button clicked without filling any value on Name");
		mobileProspectiveStudentPage.verifyPleaseEnterValidFirstNameErrorMessage();
		ExtentTestManager.getTest().pass("PleaseEnterValidFirstNameErrorMessage is verified");
		mobileProspectiveStudentPage.verifyPleaseEnterValidLastNameErrorMessage();
		ExtentTestManager.getTest().pass("PleaseEnterValidLastNameErrorMessage is verified");
		mobileProspectiveStudentPage.verifyPleaseEnterValidDOBErrorMessage();
		ExtentTestManager.getTest().pass("PleaseEnterValidDOBErrorMessage is verified");		
		otherPage.enterFirstName(setData.get("FirstName"));
		ExtentTestManager.getTest().pass("Enter the firstname");
		otherPage.enterLastName(setData.get("LastName"));
		ExtentTestManager.getTest().pass("Enter the lastname");
		mobileCifLogin.enterDOB(setData.get("DoB"));
		ExtentTestManager.getTest().pass("Enter the dob");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.enterPostalCode(setData.get("PostalCode"));
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileProspectiveStudentPage.enterCurrentHighSchoolName();
		ExtentTestManager.getTest().pass("CurrentHighSchoolName is entered");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileProspectiveStudentPage.clickIntendedMajorDropdown();
		mobileProspectiveStudentPage.enterIntendedMajorDropdown("Anthropology");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileRegistrationLegacyFormPage.selectSATScore();
		mobileRegistrationLegacyFormPage.selectACTScore();
		mobileRegistrationLegacyFormPage.selectGPAScore(setData.get("GpaScore"));
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.enterPhoneNumber(setData.get("PhoneNo"));
		mobileRegistrationLegacyFormPage.selectGenderDropdownOptionDynamic();
		ExtentTestManager.getTest().pass("Gender is selected");
		mobileCifLogin.clickAcknowledgementCheckbox();
		ExtentTestManager.getTest().pass("AcknowledgementCheckbox is clicked");
		otherPage.clickDoneButton();
		ExtentTestManager.getTest().pass("Done button is clicked");
		otherPage.verifyGetReadyMessage();
		ExtentTestManager.getTest().pass("Get ready message is verified");
	}

	@Test   
	@Parameters({"browser"})
	public void C16449_ParentGuardianScorePage(@Optional("IamOptional")String browser) throws Exception{
		System.err.println("MobileCIF - C16449_Parent_Guardian_ScorePage ["+browserName+"]");
		//		ExtentTestManager.getTest().info(MarkupHelper.createLabel("C16449_Parent_Guardian_ScorePage", ExtentColor.BLUE));
		ExtentTestManager.getTest().assignAuthor(browserName);
		ExtentTestManager.getTest().assignCategory(browserName);
		ExtentTestManager.getTest().generateLog(Status.INFO, "MobileCIF - C16449_Parent_Guardian_ScorePage ["+browserName+"]");
		ExtentTestManager.getTest().info(MarkupHelper.createLabel("MobileCIF - C16449_Parent_Guardian_ScorePage ["+browserName+"]", ExtentColor.RED));

		Map<String, String> setData = otherPage.setData();
		mobileCifLogin.navigateToMobileCIFLogin(url);
		ExtentTestManager.getTest().pass("Login to application with Mobile CIF url");
		mobileCifLogin.switchToTheVirtualtourFrame();
		otherPage.verifyWelcomeStonybrookHeader();
		cifLogin.verifyAreYouLabel();
		mobileParentAndGuardianPage.clickParentGuardianButton();
		ExtentTestManager.getTest().pass("ParentGuardianButton is clicked");
		mobileParentAndGuardianPage.clickParentGuardianCollegeGraduateButton();
		ExtentTestManager.getTest().pass("ParentGuardianCollegeGraduateButton is clicked");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		otherPage.enterEmail(setData.get("EmailID"));
		ExtentTestManager.getTest().pass("Enter the email");
		otherPage.enterFirstName(setData.get("FirstName"));
		ExtentTestManager.getTest().pass("Enter the firstname");
		otherPage.enterLastName(setData.get("LastName"));
		ExtentTestManager.getTest().pass("Enter the lastname");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		otherPage.enterEmail(setData.get("EmailID"));
		ExtentTestManager.getTest().pass("Enter the email");
		otherPage.enterFirstName(setData.get("FirstName"));
		ExtentTestManager.getTest().pass("Enter the firstname");
		otherPage.enterLastName(setData.get("LastName"));
		ExtentTestManager.getTest().pass("Enter the lastname");
		ExtentTestManager.getTest().pass("Next button clicked without filling DOB");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.enterDOB(setData.get("DoB"));
		ExtentTestManager.getTest().pass("Enter the dob");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.enterPostalCode(setData.get("PostalCode"));
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileParentAndGuardianPage.enterTheNameOfTheChildsCollageGraduate();
		ExtentTestManager.getTest().pass("Name of the College where Child Graduated is entered");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileParentAndGuardianPage.enterIndendedMajorDropdown();
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.enterInvalidSatScoreAndVerifyTheErrorMessageInParentSide();
		mobileCifLogin.enterChildsSatScoreTextbox();
		mobileCifLogin.enterInvalidActScoreAndVerifyTheErrorMessageInParentSide();
		mobileCifLogin.enterActScoreTextbox();
		mobileCifLogin.enterInvalidGpacoreAndVerifyTheErrorMessageInParentSide();
		mobileCifLogin.enterGpaScoreTextbox();
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.enterPhoneNumber(setData.get("PhoneNo"));
		mobileRegistrationLegacyFormPage.selectGenderDropdownOptionDynamic();
		ExtentTestManager.getTest().pass("Gender is selected");
		mobileCifLogin.clickAcknowledgementCheckbox();
		ExtentTestManager.getTest().pass("Acknowledgement Checkbox is clicked");
		otherPage.clickDoneButton();
		ExtentTestManager.getTest().pass("Done button is clicked");
		otherPage.verifyGetReadyMessage();
		ExtentTestManager.getTest().pass("Get ready message is verified");
	}

	@Test   
	@Parameters({"browser"})
	public void C16451_ParentGuardianAdditionalInformation(@Optional("IamOptional")String browser) throws Exception{
		System.err.println("MobileCIF - C16451_Parent_Guardian_Additional_Information ["+browserName+"]");
		//		ExtentTestManager.getTest().info(MarkupHelper.createLabel("C16451_Parent_Guardian_Additional_Information", ExtentColor.BLUE));
		ExtentTestManager.getTest().assignAuthor(browserName);
		ExtentTestManager.getTest().assignCategory(browserName);
		ExtentTestManager.getTest().generateLog(Status.INFO, "MobileCIF - C16451_Parent_Guardian_Additional_Information ["+browserName+"]");
		ExtentTestManager.getTest().info(MarkupHelper.createLabel("MobileCIF - C16451_Parent_Guardian_Additional_Information ["+browserName+"]", ExtentColor.RED));

		Map<String, String> setData = otherPage.setData();
		mobileCifLogin.navigateToMobileCIFLogin(url);
		ExtentTestManager.getTest().pass("Login to application with Mobile CIF url");
		mobileCifLogin.switchToTheVirtualtourFrame();
		otherPage.verifyWelcomeStonybrookHeader();
		cifLogin.verifyAreYouLabel();
		mobileParentAndGuardianPage.clickParentGuardianButton();
		ExtentTestManager.getTest().pass("ParentGuardianButton is clicked");
		mobileParentAndGuardianPage.clickParentGuardianCollegeGraduateButton();
		ExtentTestManager.getTest().pass("ParentGuardianCollegeGraduateButton is clicked");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		otherPage.enterEmail(setData.get("EmailID"));
		ExtentTestManager.getTest().pass("Enter the email");
		otherPage.enterFirstName(setData.get("FirstName"));
		ExtentTestManager.getTest().pass("Enter the firstname");
		otherPage.enterLastName(setData.get("LastName"));
		ExtentTestManager.getTest().pass("Enter the lastname");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		otherPage.enterEmail(setData.get("EmailID"));
		ExtentTestManager.getTest().pass("Enter the email");
		otherPage.enterFirstName(setData.get("FirstName"));
		ExtentTestManager.getTest().pass("Enter the firstname");
		otherPage.enterLastName(setData.get("LastName"));
		ExtentTestManager.getTest().pass("Enter the lastname");
		mobileCifLogin.enterDOB(setData.get("DoB"));
		ExtentTestManager.getTest().pass("Enter the dob");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.enterPostalCode(setData.get("PostalCode"));
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileParentAndGuardianPage.enterTheNameOfTheChildsCollageGraduate();
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileProspectiveStudentPage.clickIntendedMajorDropdown();
		mobileCifLogin.enterIntendedMajorDropdown();
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.enterChildsSatScoreTextbox();
		mobileRegistrationLegacyFormPage.selectACTScore();
		mobileRegistrationLegacyFormPage.selectGPAScore(setData.get("GpaScore"));
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.enterPhoneNumber(setData.get("PhoneNo"));
		mobileParentAndGuardianPage.enterPhoneNumber(setData.get("PhoneNo"));
		mobileRegistrationLegacyFormPage.selectGenderDropdownOptionDynamic();
		ExtentTestManager.getTest().pass("Gender is selected");
		mobileCifLogin.clickAcknowledgementCheckbox();
		ExtentTestManager.getTest().pass("Acknowledgement Checkbox is clicked");
		otherPage.clickDoneButton();
		ExtentTestManager.getTest().pass("Done button is clicked");
		otherPage.verifyGetReadyMessage();
		ExtentTestManager.getTest().pass("Get ready message is verified");
	}

	@Test   
	@Parameters({"browser"})  
	public void C16450_VerifyTheUserCanRegisterAsProspectiveStudentHighSchoolStudentDemographic(@Optional("IamOptional")String browser) throws Exception{
		System.err.println("MobileCIF_C16450_VerifyTheUserCanRegisterAsProspectiveStudentHighSchoolStudentDemographic ["+browserName+"]");
		//		ExtentTestManager.getTest().info(MarkupHelper.createLabel("C16450_VerifyTheUserCanRegisterAsProspectiveStudentHighSchoolStudentDemographic", ExtentColor.BLUE));
		ExtentTestManager.getTest().assignAuthor(browserName);
		ExtentTestManager.getTest().assignCategory(browserName);
		ExtentTestManager.getTest().generateLog(Status.INFO, "MobileCIF_C16450_VerifyTheUserCanRegisterAsProspectiveStudentHighSchoolStudentDemographic ["+browserName+"]");
		ExtentTestManager.getTest().info(MarkupHelper.createLabel("MobileCIF_C16450_VerifyTheUserCanRegisterAsProspectiveStudentHighSchoolStudentDemographic ["+browserName+"]", ExtentColor.RED));

		Map<String, String> setData = otherPage.setData();
		mobileCifLogin.navigateToMobileCIFLogin(url);
		ExtentTestManager.getTest().pass("Login to application with Mobile CIF url");
		mobileCifLogin.switchToTheVirtualtourFrame();
		otherPage.verifyWelcomeStonybrookHeader();
		cifLogin.verifyAreYouLabel();
		cifLogin.clickProspectiveStudentButton();
		ExtentTestManager.getTest().pass("prospective_student is clicked");
		mobileProspectiveStudentPage.clickProspectiveStudentMiddleSchoolStudentButton();
		otherPage.clickNextButton();	
		ExtentTestManager.getTest().pass("Next button is clicked");
		otherPage.enterFirstName(setData.get("FirstName"));
		ExtentTestManager.getTest().pass("Enter the firstname");
		otherPage.enterLastName(setData.get("LastName"));
		ExtentTestManager.getTest().pass("Enter the lastname");
		mobileCifLogin.enterDOB(setData.get("DoB"));
		ExtentTestManager.getTest().pass("Enter the dob");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.clickWhereAreYouFromDropdown();
		ExtentTestManager.getTest().pass("where_are_you_from_dropdown is clicked");
		mobileCifLogin.clickCanadaDropdownValue();
		ExtentTestManager.getTest().pass("canada_dropdown_value is clicked");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileProspectiveStudentPage.verifyEnterValidPostalCodeAlertMessage();
		ExtentTestManager.getTest().pass("Enter ValidPostalCodeAlertMessage is verified");
		mobileCifLogin.enterPostalCode("9");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		ExtentTestManager.getTest().pass("Enter invalid postal code and click next button");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileProspectiveStudentPage.verifyEnterValidPostalCodeAlertMessage();
		ExtentTestManager.getTest().pass("Enter ValidPostalCodeAlertMessage is verified");
		mobileCifLogin.enterPostalCode("9@");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Enter invalid postal code and click next button");
		mobileProspectiveStudentPage.verifyEnterValidPostalCodeAlertMessage();
		ExtentTestManager.getTest().pass("Enter ValidPostalCodeAlertMessage is verified");
		mobileCifLogin.enterPostalCode("H1H1H1");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Enter invalid postal code and click next button");
		mobileProspectiveStudentPage.verifyEnterValidPostalCodeAlertMessage();
		mobileCifLogin.enterPostalCode(setData.get("PostalCode"));
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileRegistrationLegacyFormPage.selectGenderDropdownOptionDynamic();
		ExtentTestManager.getTest().pass("Gender is selected");
		otherPage.clickDoneButton();
		ExtentTestManager.getTest().pass("Done button is clicked");
		otherPage.verifyGetReadyMessage();
		ExtentTestManager.getTest().pass("Get ready message is verified");
	}

	@Test   
	@Parameters({"browser"})  
	public void C16458_VerifyTheUserCanRegisterAsParentHighSchoolStudentDemographic(@Optional("IamOptional")String browser) throws Exception{
		System.err.println("MobileCIF_C16458_VerifyTheUserCanRegisterAsParentHighSchoolStudentDemographic ["+browserName+"]");
		//		ExtentTestManager.getTest().info(MarkupHelper.createLabel("C16458_VerifyTheUserCanRegisterAsParentHighSchoolStudentDemographic and C53278_Verify Registration from Embed (VT opens from Client webpage)", ExtentColor.BLUE));
		ExtentTestManager.getTest().assignAuthor(browserName);
		ExtentTestManager.getTest().assignCategory(browserName);
		ExtentTestManager.getTest().generateLog(Status.INFO, "C16458_VerifyTheUserCanRegisterAsParentHighSchoolStudentDemographic and C53278_Verify Registration from Embed (VT opens from Client webpage) ["+browserName+"]");
		ExtentTestManager.getTest().info(MarkupHelper.createLabel("C16458_VerifyTheUserCanRegisterAsParentHighSchoolStudentDemographic and C53278_Verify Registration from Embed (VT opens from Client webpage) ["+browserName+"]", ExtentColor.RED));

		Map<String, String> setData = otherPage.setData();
		mobileCifLogin.navigateToMobileCIFLogin(url);
		ExtentTestManager.getTest().pass("Login to application with Mobile CIF url");
		mobileCifLogin.switchToTheVirtualtourFrame();
		otherPage.verifyWelcomeStonybrookHeader();
		cifLogin.verifyAreYouLabel();
		mobileParentAndGuardianPage.clickParentGuardianButton();
		mobileParentAndGuardianPage.clickParentGuardianHighSchoolStudentButton();
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		otherPage.enterFirstName(setData.get("FirstName"));
		ExtentTestManager.getTest().pass("Enter the firstname");
		otherPage.enterLastName(setData.get("LastName"));
		ExtentTestManager.getTest().pass("Enter the lastname");
		otherPage.clickNextButton();
		mobileCifLogin.verifyPleaseEnterValidEmailErrorMessage();
		ExtentTestManager.getTest().pass("PleaseEnterValidDOBErrorMessage is verified");
		mobileCifLogin.enterEmail(setData.get("EmailID"));
		ExtentTestManager.getTest().pass("Enter the email");
		//mobileCifLogin.enterParentDOB(setData.get("DoB"));
		//ExtentTestManager.getTest().pass("Enter the dob");
		otherPage.clickNextButton();
		otherPage.enterEmail(setData.get("EmailID"));
		ExtentTestManager.getTest().pass("Enter the email");
		otherPage.enterFirstName(setData.get("FirstName"));
		ExtentTestManager.getTest().pass("Enter the firstname");
		otherPage.enterLastName(setData.get("LastName"));
		ExtentTestManager.getTest().pass("Enter the lastname");
		mobileCifLogin.enterDOB(setData.get("DoB"));
		ExtentTestManager.getTest().pass("Enter the dob");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		ExtentTestManager.getTest().pass("Click next without enter postal code");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileProspectiveStudentPage.verifyEnterValidPostalCodeAlertMessage();
		ExtentTestManager.getTest().pass("Enter ValidPostalCodeAlertMessage is verified");
		mobileCifLogin.enterPostalCode("9");
		ExtentTestManager.getTest().pass("Enter invalid postal code and click next button");
		otherPage.clickNextButton();
		mobileProspectiveStudentPage.verifyEnterValidPostalCodeAlertMessage();
		ExtentTestManager.getTest().pass("Enter ValidPostalCodeAlertMessage is verified");
		mobileCifLogin.enterPostalCode("9@");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Enter invalid postal code and click next button");
		mobileProspectiveStudentPage.verifyEnterValidPostalCodeAlertMessage();
		ExtentTestManager.getTest().pass("Enter ValidPostalCodeAlertMessage is verified");
		mobileCifLogin.enterPostalCode("H1H1H1");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Enter invalid postal code and click next button");
		mobileProspectiveStudentPage.verifyEnterValidPostalCodeAlertMessage();
		mobileCifLogin.enterPostalCode(setData.get("PostalCode"));
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		otherPage.clickNextButton();
		mobileProspectiveStudentPage.enterCurrentHighSchoolName();
		ExtentTestManager.getTest().pass("CurrentHighSchoolName is entered");
		mobileProspectiveStudentPage.clickIntendedMajorDropdown();
		mobileCifLogin.enterIntendedMajorDropdown();
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Click on next button");
		mobileCifLogin.enterChildsSatScoreTextbox();
		ExtentTestManager.getTest().pass("SAT score is entered");
		mobileRegistrationLegacyFormPage.selectACTScore();
		ExtentTestManager.getTest().pass("ACT score is entered");
		mobileRegistrationLegacyFormPage.selectGPAScore(setData.get("GpaScore"));
		ExtentTestManager.getTest().pass("GPA score is entered");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.enterPhoneNumber(setData.get("PhoneNo"));
		mobileRegistrationLegacyFormPage.selectGenderDropdownOptionDynamic();
		ExtentTestManager.getTest().pass("Gender is selected");
		mobileCifLogin.clickAcknowledgementCheckbox();
		ExtentTestManager.getTest().pass("Acknowledgement Checkbox is clicked");
		otherPage.clickDoneButton();
		ExtentTestManager.getTest().pass("Done button is clicked");
		otherPage.verifyGetReadyMessage();
		ExtentTestManager.getTest().pass("Get ready message is verified");
	}

	@Test   
	@Parameters({"browser"})  
	public void C16460_VerifyTheUserCanRegisterAsOtherCurrentStudentEmail(@Optional("IamOptional")String browser) throws Exception{
		System.err.println("MobileCIF_C16460_VerifyTheUserCanRegisterAsOtherCurrentStudentEMAIL ["+browserName+"]");
		//		ExtentTestManager.getTest().info(MarkupHelper.createLabel("C16460_VerifyTheUserCanRegisterAsOtherCurrentStudentEMAIL", ExtentColor.BLUE));
		ExtentTestManager.getTest().assignAuthor(browserName);
		ExtentTestManager.getTest().assignCategory(browserName);
		ExtentTestManager.getTest().generateLog(Status.INFO, "MobileCIF_C16460_VerifyTheUserCanRegisterAsOtherCurrentStudentEMAIL ["+browserName+"]");
		ExtentTestManager.getTest().info(MarkupHelper.createLabel("MobileCIF_C16460_VerifyTheUserCanRegisterAsOtherCurrentStudentEMAIL ["+browserName+"]", ExtentColor.RED));

		Map<String, String> setData = otherPage.setData();
		mobileCifLogin.navigateToMobileCIFLogin(url);
		ExtentTestManager.getTest().pass("Login to application with Mobile CIF url");
		mobileCifLogin.switchToTheVirtualtourFrame();
		otherPage.verifyWelcomeStonybrookHeader();
		cifLogin.verifyAreYouLabel();
		otherPage.clickOtherButton();
		ExtentTestManager.getTest().pass("other_button is clicked");
		otherPage.verifyWhatDescribeYouText();
		ExtentTestManager.getTest().pass("What Best Describes You? Text displayed on the Registration page");
		otherPage.clickCurrentStudentButton();
		ExtentTestManager.getTest().pass("CurrentStudentButton is clicked");
		mobileCifLogin.verifyYourEmailPlaceholderTextbox();
		ExtentTestManager.getTest().pass("YourEmailPlaceholderTextbox is verified");
		mobileCifLogin.verifyFirstnamePlaceholderTextbox();
		ExtentTestManager.getTest().pass("FirstnamePlaceholderTextbox is verified");
		mobileCifLogin.verifyLastnamePlaceholderTextbox();
		ExtentTestManager.getTest().pass("LastnamePlaceholderTextbox is verified");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button clicked without filling any value on Name & DOB page page");
		mobileProspectiveStudentPage.verifyPleaseEnterValidFirstNameErrorMessage();
		ExtentTestManager.getTest().pass("PleaseEnterValidFirstNameErrorMessage is verified");
		mobileProspectiveStudentPage.verifyPleaseEnterValidLastNameErrorMessage();
		ExtentTestManager.getTest().pass("PleaseEnterValidLastNameErrorMessage is verified");
		mobileProspectiveStudentPage.verifyPleaseEnterValidEmailIDErrorMessage();
		ExtentTestManager.getTest().pass("PleaseEnterValidEmailIDErrorMessage is verified");
		mobileProspectiveStudentPage.verifyPleaseEnterValidDOBErrorMessage();
		ExtentTestManager.getTest().pass("PleaseEnterValidDOBErrorMessage is verified");
		otherPage.enterFirstName(setData.get("FirstName"));
		ExtentTestManager.getTest().pass("Enter the firstname");
		otherPage.enterLastName(setData.get("LastName"));
		ExtentTestManager.getTest().pass("Enter the lastname");
		mobileCifLogin.enterDOB(setData.get("DoB"));
		ExtentTestManager.getTest().pass("Enter the dob");
		otherPage.clickNextButton();
		otherPage.enterEmail("Testeab.com");
		ExtentTestManager.getTest().pass("Enter the invalid email id");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("PleaseEnterValidEmailIDErrorMessage is verified");
		otherPage.enterEmail("TTest");
		ExtentTestManager.getTest().pass("Enter the invalid email id");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("PleaseEnterValidEmailIDErrorMessage is verified");
		otherPage.enterEmail("Test@eabcom");
		ExtentTestManager.getTest().pass("Enter the invalid email id");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("PleaseEnterValidEmailIDErrorMessage is verified");
		otherPage.enterEmail("Test@eabcom");
		ExtentTestManager.getTest().pass("Enter the invalid email id");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("PleaseEnterValidEmailIDErrorMessage is verified");
		otherPage.enterEmail(setData.get("EmailID"));
		ExtentTestManager.getTest().pass("Enter the valid email");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		otherPage.verifyPrivacyPolicyLink();
		ExtentTestManager.getTest().pass("PrivacyPolicyLink is verified");
		otherPage.verifyTermsOfUseLink();
		ExtentTestManager.getTest().pass("TermsOfUseLink is verified");
		otherPage.verifyAlmostDoneMessage();
		ExtentTestManager.getTest().pass("AlmostDoneMessage is verified");
		otherPage.verifyAlmostDoneMessageBar();
		ExtentTestManager.getTest().pass("AlmostDoneMessage bar is verified");
		otherPage.clickDoneButton();
		ExtentTestManager.getTest().pass("Done button is clicked");
		otherPage.verifyGetReadyMessage();
		ExtentTestManager.getTest().pass("GetReadyMessage is verified");
	}

	@Test   
	@Parameters({"browser"})  
	public void C16461_VerifyTheUserCanRegisterAsOtherCurrentStudentName(@Optional("IamOptional")String browser) throws Exception{
		System.err.println("MobileCIF_C16461_VerifyTheUserCanRegisterAsOtherCurrentStudentName ["+browserName+"]");
		//		ExtentTestManager.getTest().info(MarkupHelper.createLabel("C16461_VerifyTheUserCanRegisterAsOtherCurrentStudentName", ExtentColor.BLUE));
		ExtentTestManager.getTest().assignAuthor(browserName);
		ExtentTestManager.getTest().assignCategory(browserName);
		ExtentTestManager.getTest().generateLog(Status.INFO, "MobileCIF_C16461_VerifyTheUserCanRegisterAsOtherCurrentStudentName ["+browserName+"]");
		ExtentTestManager.getTest().info(MarkupHelper.createLabel("MobileCIF_C16461_VerifyTheUserCanRegisterAsOtherCurrentStudentName ["+browserName+"]", ExtentColor.RED));

		Map<String, String> setData = otherPage.setData();
		mobileCifLogin.navigateToMobileCIFLogin(url);
		ExtentTestManager.getTest().pass("Login to application with Mobile CIF url");
		mobileCifLogin.switchToTheVirtualtourFrame();
		otherPage.verifyWelcomeStonybrookHeader();
		cifLogin.verifyAreYouLabel();
		otherPage.clickOtherButton();
		ExtentTestManager.getTest().pass("other_button is clicked");
		otherPage.verifyWhatDescribeYouText();
		ExtentTestManager.getTest().pass("What Best Describes You? Text displayed on the Registration page");
		otherPage.clickCurrentStudentButton();
		ExtentTestManager.getTest().pass("CurrentStudentButton is clicked");
		mobileCifLogin.verifyYourEmailPlaceholderTextbox();
		ExtentTestManager.getTest().pass("YourEmailPlaceholderTextbox is verified");
		mobileCifLogin.verifyFirstnamePlaceholderTextbox();
		ExtentTestManager.getTest().pass("FirstnamePlaceholderTextbox is verified");
		mobileCifLogin.verifyLastnamePlaceholderTextbox();
		ExtentTestManager.getTest().pass("LastnamePlaceholderTextbox is verified");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button clicked without filling any value on Name & DOB page page");
		mobileProspectiveStudentPage.verifyPleaseEnterValidFirstNameErrorMessage();
		ExtentTestManager.getTest().pass("PleaseEnterValidFirstNameErrorMessage is verified");
		mobileProspectiveStudentPage.verifyPleaseEnterValidLastNameErrorMessage();
		ExtentTestManager.getTest().pass("PleaseEnterValidLastNameErrorMessage is verified");
		mobileProspectiveStudentPage.verifyPleaseEnterValidEmailIDErrorMessage();
		ExtentTestManager.getTest().pass("PleaseEnterValidEmailIDErrorMessage is verified");
		mobileProspectiveStudentPage.verifyPleaseEnterValidDOBErrorMessage();
		ExtentTestManager.getTest().pass("PleaseEnterValidDOBErrorMessage is verified");
		otherPage.enterFirstName(setData.get("FirstName"));
		ExtentTestManager.getTest().pass("Enter the firstname");
		otherPage.enterLastName(setData.get("LastName"));
		ExtentTestManager.getTest().pass("Enter the lastname");
		mobileCifLogin.enterDOB(setData.get("DoB"));
		ExtentTestManager.getTest().pass("Enter the dob");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		otherPage.enterEmail("Testeab.com");
		ExtentTestManager.getTest().pass("Enter the invalid email id");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("PleaseEnterValidEmailIDErrorMessage is verified");
		otherPage.enterEmail("TTest");
		ExtentTestManager.getTest().pass("Enter the invalid email id");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("PleaseEnterValidEmailIDErrorMessage is verified");
		otherPage.enterEmail("Test@eabcom");
		ExtentTestManager.getTest().pass("Enter the invalid email id");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("PleaseEnterValidEmailIDErrorMessage is verified");
		otherPage.enterEmail("Test@eabcom");
		ExtentTestManager.getTest().pass("Enter the invalid email id");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("PleaseEnterValidEmailIDErrorMessage is verified");
		otherPage.enterEmail(setData.get("EmailID"));
		ExtentTestManager.getTest().pass("Enter the valid email");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		otherPage.verifyPrivacyPolicyLink();
		ExtentTestManager.getTest().pass("PrivacyPolicyLink is verified");
		otherPage.verifyTermsOfUseLink();
		ExtentTestManager.getTest().pass("TermsOfUseLink is verified");
		otherPage.verifyAlmostDoneMessage();
		ExtentTestManager.getTest().pass("AlmostDoneMessage is verified");
		otherPage.verifyAlmostDoneMessageBar();
		ExtentTestManager.getTest().pass("AlmostDoneMessage bar is verified");
		otherPage.clickDoneButton();
		ExtentTestManager.getTest().pass("Done button is clicked");
		otherPage.verifyGetReadyMessage();
		ExtentTestManager.getTest().pass("GetReadyMessage is verified");
	}

	@Test   
	@Parameters({"browser"})
	public void C16459_C16452_VerifyTheUserCanRegisterAsParentHighSchoolStudentAdditionalInformation(@Optional("IamOptional")String browser) throws Exception{
		System.err.println("MobileCIF_C16459_C16452_VerifyTheUserCanRegisterAsParentHighSchoolStudentAdditionalInformation ["+browserName+"]");
		//		ExtentTestManager.getTest().info(MarkupHelper.createLabel("C16459_C16452_VerifyTheUserCanRegisterAsParentHighSchoolStudentAdditionalInformation", ExtentColor.BLUE));
		ExtentTestManager.getTest().assignAuthor(browserName);
		ExtentTestManager.getTest().assignCategory(browserName);
		ExtentTestManager.getTest().generateLog(Status.INFO, "MobileCIF_C16459_C16452_VerifyTheUserCanRegisterAsParentHighSchoolStudentAdditionalInformation ["+browserName+"]");
		ExtentTestManager.getTest().info(MarkupHelper.createLabel("MobileCIF_C16459_C16452_VerifyTheUserCanRegisterAsParentHighSchoolStudentAdditionalInformation ["+browserName+"]", ExtentColor.RED));

		Map<String, String> setData = otherPage.setData();
		mobileCifLogin.navigateToMobileCIFLogin(url);
		ExtentTestManager.getTest().pass("Login to application with Mobile CIF url");
		mobileCifLogin.switchToTheVirtualtourFrame();
		otherPage.verifyWelcomeStonybrookHeader();
		cifLogin.verifyAreYouLabel();
		mobileParentAndGuardianPage.clickParentGuardianButton();
		ExtentTestManager.getTest().pass("ParentGuardian button is clicked");
		mobileParentAndGuardianPage.clickParentGuardianHighSchoolStudentButton();
		ExtentTestManager.getTest().pass("ParentGuardianHighSchoolStudent button is clicked");
		mobileCifLogin.verifyChildsHighSchoolGraduationYearDropdownDefaultValue();
		ExtentTestManager.getTest().pass("High School Graduation Year Dropdown Default Value is  appears");
		mobileCifLogin.verifyChildsIntendedEnrollmentYearAndTermLabel();
		ExtentTestManager.getTest().pass("High School INTENDED ENROLLMENT YEAR & TERM label appears");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		otherPage.enterEmail(setData.get("EmailID"));
		ExtentTestManager.getTest().pass("Enter the email");
		otherPage.enterFirstName(setData.get("FirstName"));
		ExtentTestManager.getTest().pass("Enter the firstname");
		otherPage.enterLastName(setData.get("LastName"));
		ExtentTestManager.getTest().pass("Enter the lastname");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		otherPage.enterEmail(setData.get("EmailID"));
		ExtentTestManager.getTest().pass("Enter the email");
		otherPage.enterFirstName(setData.get("FirstName"));
		ExtentTestManager.getTest().pass("Enter the firstname");
		otherPage.enterLastName(setData.get("LastName"));
		ExtentTestManager.getTest().pass("Enter the lastname");
		mobileCifLogin.enterDOB(setData.get("DoB"));
		ExtentTestManager.getTest().pass("Enter the dob");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.enterPostalCode(setData.get("PostalCode"));
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileParentAndGuardianPage.enterTheNameOfTheChildsCollageGraduate();
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileProspectiveStudentPage.clickIntendedMajorDropdown();
		mobileCifLogin.enterIntendedMajorDropdown();
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Click on next button");
		mobileCifLogin.enterChildsSatScoreTextbox();
		mobileRegistrationLegacyFormPage.selectACTScore();
		mobileRegistrationLegacyFormPage.selectGPAScore(setData.get("GpaScore"));
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.enterPhoneNumber(setData.get("PhoneNo"));
		mobileCifLogin.clickGenderDropdown();
		ExtentTestManager.getTest().pass("Gender Dropdown is clicked");
		mobileCifLogin.selectGenderMaleOption();
		ExtentTestManager.getTest().pass("Gender Male Option is selected");
		mobileCifLogin.clickAcknowledgementCheckbox();
		mobileRegistrationLegacyFormPage.verifyChildEthnicityLabel();
		ExtentTestManager.getTest().pass("verifyChildEthnicityLabel is verified");
		mobileCifLogin.verifyChildEthnicityDropdown();
		ExtentTestManager.getTest().pass("ChildEthnicityDropdown is verified");
		otherPage.clickDoneButton();
		ExtentTestManager.getTest().pass("Done button is clicked");
		otherPage.verifyGetReadyMessage();
		ExtentTestManager.getTest().pass("Get ready message is verified");
	}

	@Test   
	@Parameters({"browser"})  
	public void C16444_MiddleSchoolStudentWhoTheyIntendToBe(@Optional("IamOptional")String browser) throws Exception{
		System.err.println("MobileCIF_C16444_MiddleSchoolStudentWhoTheyIntendToBe ["+browserName+"]");
		//		ExtentTestManager.getTest().info(MarkupHelper.createLabel("C16444_MiddleSchoolStudentWhoTheyIntendToBe", ExtentColor.BLUE));
		ExtentTestManager.getTest().assignAuthor(browserName);
		ExtentTestManager.getTest().assignCategory(browserName);
		ExtentTestManager.getTest().generateLog(Status.INFO, "MobileCIF_C16444_MiddleSchoolStudentWhoTheyIntendToBe ["+browserName+"]");
		ExtentTestManager.getTest().info(MarkupHelper.createLabel("MobileCIF_C16444_MiddleSchoolStudentWhoTheyIntendToBe ["+browserName+"]", ExtentColor.RED));

		Map<String, String> setData = otherPage.setData();
		mobileCifLogin.navigateToMobileCIFLogin(url);
		ExtentTestManager.getTest().pass("Login to application with Mobile CIF url");
		mobileCifLogin.switchToTheVirtualtourFrame();
		otherPage.verifyWelcomeStonybrookHeader();
		cifLogin.verifyAreYouLabel();
		cifLogin.clickProspectiveStudentButton();
		ExtentTestManager.getTest().pass("prospective_student is clicked");
		mobileProspectiveStudentPage.clickProspectiveStudentMiddleSchoolStudentButton();
		mobileProspectiveStudentPage.verifyHighSchoolIntendedEnrollmentYearTermLabel();
		ExtentTestManager.getTest().pass("High School INTENDED ENROLLMENT YEAR & TERM label appears");
		otherPage.clickNextButton();	
		otherPage.enterFirstName(setData.get("FirstName"));
		ExtentTestManager.getTest().pass("Enter the firstname");
		otherPage.enterLastName(setData.get("LastName"));
		ExtentTestManager.getTest().pass("Enter the lastname");
		mobileCifLogin.enterDOB(setData.get("DoB"));
		ExtentTestManager.getTest().pass("Enter the dob");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.enterPostalCode(setData.get("PostalCode"));
		ExtentTestManager.getTest().pass("PostalCode is entered");
		otherPage.clickNextButton();	
		ExtentTestManager.getTest().pass("Click on next button");
		mobileRegistrationLegacyFormPage.selectGenderDropdownOptionDynamic();
		ExtentTestManager.getTest().pass("Gender is selected");
		otherPage.clickDoneButton();
		ExtentTestManager.getTest().pass("Click on done button");
		otherPage.verifyGetReadyMessage();
		ExtentTestManager.getTest().pass("Get ready message is verified");
	}

	@Test   
	@Parameters({"browser"})  
	public void C16436_VerifyVisitorTypeStudentOptionsPage(@Optional("IamOptional")String browser) throws Exception{
		System.err.println("MobileCIF - C16436_VerifyVisitorTypeStudentOptionsPage ["+browserName+"]");
		//		ExtentTestManager.getTest().info(MarkupHelper.createLabel("C16436_VerifyVisitorTypeStudentOptionsPage", ExtentColor.BLUE));
		ExtentTestManager.getTest().assignAuthor(browserName);
		ExtentTestManager.getTest().assignCategory(browserName);
		ExtentTestManager.getTest().generateLog(Status.INFO, "MobileCIF - C16436_VerifyVisitorTypeStudentOptionsPage ["+browserName+"]");
		ExtentTestManager.getTest().info(MarkupHelper.createLabel("MobileCIF - C16436_VerifyVisitorTypeStudentOptionsPage ["+browserName+"]", ExtentColor.RED));

		mobileCifLogin.navigateToMobileCIFLogin(url);
		ExtentTestManager.getTest().pass("Login to application with Mobile CIF url");
		mobileCifLogin.switchToTheVirtualtourFrame();
		otherPage.verifyWelcomeStonybrookHeader();
		ExtentTestManager.getTest().pass("WelcomeStonybrookHeader is verified");
		cifLogin.verifyAreYouLabel();
		ExtentTestManager.getTest().pass("AreYouLabel is verified");
		cifLogin.clickProspectiveStudentButton();
		ExtentTestManager.getTest().pass("prospective_student is clicked");
		otherPage.verifyWhatDescribeYouText();
		ExtentTestManager.getTest().pass("What Best Describes You? Text displayed on the ProspectiveStudentOptions Page");
		mobileCifLogin.verifyProspectiveStudentMiddleSchoolStudentButton();
		ExtentTestManager.getTest().pass("ProspectiveStudentMiddleSchoolStudentButton is verified");
		mobileCifLogin.verifyProspectiveStudentHighSchoolStudentButton();
		ExtentTestManager.getTest().pass("ProspectiveStudentHighSchoolStudentButton is verified");
		mobileCifLogin.verifyProspectiveStudentCollegeStudentButton();
		ExtentTestManager.getTest().pass("ProspectiveStudentCollegeStudentButton is verified");
		mobileCifLogin.verifyCollegeGraduateButton();
		ExtentTestManager.getTest().pass("CollegeGraduateButton is verified");
		mobileCifLogin.verifyProspectiveStudentAdultLearnerButton();
		ExtentTestManager.getTest().pass("ProspectiveStudentAdultLearnerButton is verified");
		mobileCifLogin.verifyHighSchoolGraduateButton();
		ExtentTestManager.getTest().pass("HighSchoolGraduateButton is verified");
	}

	@Test   
	@Parameters({"browser"})  
	public void C16447_VerifyVerifyTheUserCanRegisterAsProspectiveStudent_HighSchoolStudent_School(@Optional("IamOptional")String browser) throws Exception{
		System.err.println("MobileCIF_C16447_VerifyVerifyTheUserCanRegisterAsProspectiveStudent_HighSchoolStudent_School ["+browserName+"]");
		//		ExtentTestManager.getTest().info(MarkupHelper.createLabel("C16447_VerifyVerifyTheUserCanRegisterAsProspectiveStudent_HighSchoolStudent_School", ExtentColor.BLUE));
		ExtentTestManager.getTest().assignAuthor(browserName);
		ExtentTestManager.getTest().assignCategory(browserName);
		ExtentTestManager.getTest().generateLog(Status.INFO, "MobileCIF_C16447_VerifyVerifyTheUserCanRegisterAsProspectiveStudent_HighSchoolStudent_School ["+browserName+"]");
		ExtentTestManager.getTest().info(MarkupHelper.createLabel("MobileCIF_C16447_VerifyVerifyTheUserCanRegisterAsProspectiveStudent_HighSchoolStudent_School ["+browserName+"]", ExtentColor.RED));

		Map<String, String> setData = otherPage.setData();
		mobileCifLogin.navigateToMobileCIFLogin(url);
		ExtentTestManager.getTest().pass("Login to application with Mobile CIF url");
		mobileCifLogin.switchToTheVirtualtourFrame();
		otherPage.verifyWelcomeStonybrookHeader();
		cifLogin.verifyAreYouLabel();
		cifLogin.clickProspectiveStudentButton();
		ExtentTestManager.getTest().pass("prospective_student is clicked");
		otherPage.verifyWhatDescribeYouText();
		ExtentTestManager.getTest().pass("What Best Describes You? Text displayed on the ProspectiveStudentOptions Page");
		mobileProspectiveStudentPage.clickProspectiveStudentHighSchoolStudentButton();
		ExtentTestManager.getTest().pass("ProspectiveStudentHighSchoolStudentButton is clicked");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.verifyYourEmailPlaceholderTextbox();
		ExtentTestManager.getTest().pass("YourEmailPlaceholderTextbox is verified");
		mobileCifLogin.verifyFirstnamePlaceholderTextbox();
		ExtentTestManager.getTest().pass("FirstnamePlaceholderTextbox is verified");
		mobileCifLogin.verifyLastnamePlaceholderTextbox();
		ExtentTestManager.getTest().pass("LastnamePlaceholderTextbox is verified");
		mobileCifLogin.verifyYourEmailLabel();
		ExtentTestManager.getTest().pass("YourEmailLabel is verified");
		mobileCifLogin.verifyFirstNameLabel();
		ExtentTestManager.getTest().pass("FirstNameLabel is verified");
		mobileCifLogin.verifyLastNameLabel();
		ExtentTestManager.getTest().pass("LastNameLabel is verified");
		otherPage.enterEmail(setData.get("EmailID"));
		ExtentTestManager.getTest().pass("Enter the email");
		otherPage.enterFirstName(setData.get("FirstName"));
		ExtentTestManager.getTest().pass("Enter the firstname");
		otherPage.enterLastName(setData.get("LastName"));
		ExtentTestManager.getTest().pass("Enter the lastname");
		mobileCifLogin.enterDOB(setData.get("DoB"));
		ExtentTestManager.getTest().pass("Enter the dob");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next button is clicked");
		mobileCifLogin.verifyWhereAreYouFromLabel();
		ExtentTestManager.getTest().pass("WhereAreYouFromLabel is verified in postal code page");
		mobileCifLogin.verifyUsaCountryDefaultSelection();
		ExtentTestManager.getTest().pass("UsaCountryDefaultSelection is verified");
		mobileCifLogin.verifyPostalPlaceholderTextbox();
		ExtentTestManager.getTest().pass("PostalPlaceholderTextbox is verified");
		mobileCifLogin.enterPostalCode(setData.get("PostalCode"));
		otherPage.clickNextButton();
		mobileCifLogin.verifySchoolPlaceholderTextbox();
		ExtentTestManager.getTest().pass("School Placeholder Textbox is verified");
		mobileProspectiveStudentPage.enterCurrentHighSchoolName();
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Click on next button");
		mobileProspectiveStudentPage.clickIntendedMajorDropdown();
		mobileCifLogin.enterIntendedMajorDropdown();
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Click on next button");
		mobileCifLogin.enterInvalidSatScoreAndVerifyTheErrorMessage();
		mobileRegistrationLegacyFormPage.selectSATScore();
		mobileCifLogin.enterInvalidActScoreAndVerifyTheErrorMessage();
		mobileRegistrationLegacyFormPage.selectACTScore();
		mobileCifLogin.enterInvalidGpacoreAndVerifyTheErrorMessage();
		mobileCifLogin.enterGpaScoreTextbox();
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Click on next button");
		mobileCifLogin.enterPhoneNumber(setData.get("PhoneNo"));
		/*mobileCifLogin.clickGenderDropdown();
		ExtentTestManager.getTest().pass("Gender Dropdown is clicked");
		mobileCifLogin.selectGenderMaleOption();
		ExtentTestManager.getTest().pass("Gender Male Option is selected");*/
		mobileRegistrationLegacyFormPage.selectGenderDropdownOptionDynamic();
		ExtentTestManager.getTest().pass("Gender is selected");
		mobileCifLogin.clickAcknowledgementCheckbox();
		ExtentTestManager.getTest().pass("Acknowledgement Checkbox is clicked");
		otherPage.clickDoneButton();
		ExtentTestManager.getTest().pass("Click on done button");
		otherPage.verifyGetReadyMessage();
		ExtentTestManager.getTest().pass("Get ready message is verified");	
	}

	@Test   
	@Parameters({"browser"})  
	public void C16448_VerifyTheUserCanRegisterAsProspectiveStudentHighSchoolStudentIndendedMajor(@Optional("IamOptional")String browser) throws Exception{
		System.err.println("MobileCIF_C16448_VerifyVerifyTheUserCanRegisterAsProspectiveStudent_HighSchoolStudent_IndendedMajor ["+browserName+"]");
		//		ExtentTestManager.getTest().info(MarkupHelper.createLabel("C16448_VerifyVerifyTheUserCanRegisterAsProspectiveStudent_HighSchoolStudent_IndendedMajor", ExtentColor.BLUE));
		ExtentTestManager.getTest().assignAuthor(browserName);
		ExtentTestManager.getTest().assignCategory(browserName);
		ExtentTestManager.getTest().generateLog(Status.INFO, "MobileCIF_C16448_VerifyVerifyTheUserCanRegisterAsProspectiveStudent_HighSchoolStudent_IndendedMajor ["+browserName+"]");
		ExtentTestManager.getTest().info(MarkupHelper.createLabel("MobileCIF_C16448_VerifyVerifyTheUserCanRegisterAsProspectiveStudent_HighSchoolStudent_IndendedMajor ["+browserName+"]", ExtentColor.RED));

		Map<String, String> setData = otherPage.setData();
		mobileCifLogin.navigateToMobileCIFLogin(url);
		ExtentTestManager.getTest().pass("Login to application with Mobile CIF url");
		mobileCifLogin.switchToTheVirtualtourFrame();
		otherPage.verifyWelcomeStonybrookHeader();
		cifLogin.verifyAreYouLabel();
		cifLogin.clickProspectiveStudentButton();
		ExtentTestManager.getTest().pass("prospective_student is clicked");
		otherPage.verifyWhatDescribeYouText();
		ExtentTestManager.getTest().pass("What Best Describes You? Text displayed on the ProspectiveStudentOptions Page");
		mobileProspectiveStudentPage.clickProspectiveStudentHighSchoolStudentButton();
		ExtentTestManager.getTest().pass("ProspectiveStudentHighSchoolStudentButton is clicked");
		mobileProspectiveStudentPage.verifyHighSchoolGraduationYearLabel();
		mobileProspectiveStudentPage.verifyHighSchoolIntendedEnrollmentYearTermLabel();
		otherPage.clickNextButton();	
		mobileCifLogin.verifyYourEmailPlaceholderTextbox();
		ExtentTestManager.getTest().pass("YourEmailPlaceholderTextbox is verified");
		mobileCifLogin.verifyFirstnamePlaceholderTextbox();
		ExtentTestManager.getTest().pass("FirstnamePlaceholderTextbox is verified");
		mobileCifLogin.verifyLastnamePlaceholderTextbox();
		ExtentTestManager.getTest().pass("LastnamePlaceholderTextbox is verified");
		mobileCifLogin.verifyYourEmailLabel();
		ExtentTestManager.getTest().pass("YourEmailLabel is verified");
		mobileCifLogin.verifyFirstNameLabel();
		ExtentTestManager.getTest().pass("FirstNameLabel is verified");
		mobileCifLogin.verifyLastNameLabel();
		ExtentTestManager.getTest().pass("LastNameLabel is verified");
		otherPage.enterEmail(setData.get("EmailID"));
		ExtentTestManager.getTest().pass("Enter the email");
		otherPage.enterFirstName(setData.get("FirstName"));
		ExtentTestManager.getTest().pass("Enter the firstname");
		otherPage.enterLastName(setData.get("LastName"));
		ExtentTestManager.getTest().pass("Enter the lastname");
		mobileCifLogin.enterDOB(setData.get("DoB"));
		ExtentTestManager.getTest().pass("Enter the dob");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next Button is clicked");
		mobileCifLogin.verifyWhereAreYouFromLabel();
		otherPage.verifyPrivacyPolicyLink();
		ExtentTestManager.getTest().pass("PrivacyPolicyLink is verified");
		otherPage.verifyTermsOfUseLink();
		ExtentTestManager.getTest().pass("TermsOfUseLink is verified");
		mobileCifLogin.enterPostalCode(setData.get("PostalCode"));
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next Button is clicked");
		mobileProspectiveStudentPage.enterCurrentHighSchoolName();
		otherPage.clickNextButton();
		mobileParentAndGuardianPage.enterIndendedMajorDropdown();
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next Button is clicked");
		mobileCifLogin.verifySatScoreLabel();
		ExtentTestManager.getTest().pass("SatScoreLabel is visible after the enter indended major");
	}

	@Test   
	@Parameters({"browser"})  
	public void C16453_VerifyTheUserCanRegisterAsParentHighSchoolStudentEmail(@Optional("IamOptional")String browser) throws Exception{
		System.err.println("MobileCIF_C16453_VerifyTheUserCanRegisterAsParentHighSchoolStudentEMAIL ["+browserName+"]");
		//		ExtentTestManager.getTest().info(MarkupHelper.createLabel("C16453_VerifyTheUserCanRegisterAsParentHighSchoolStudentEMAIL", ExtentColor.BLUE));
		ExtentTestManager.getTest().assignAuthor(browserName);
		ExtentTestManager.getTest().assignCategory(browserName);
		ExtentTestManager.getTest().generateLog(Status.INFO, "MobileCIF_C16453_VerifyTheUserCanRegisterAsParentHighSchoolStudentEMAIL ["+browserName+"]");
		ExtentTestManager.getTest().info(MarkupHelper.createLabel("MobileCIF_C16453_VerifyTheUserCanRegisterAsParentHighSchoolStudentEMAIL ["+browserName+"]", ExtentColor.RED));

		Map<String, String> setData = otherPage.setData();
		mobileCifLogin.navigateToMobileCIFLogin(url);
		ExtentTestManager.getTest().pass("Login to application with Mobile CIF url");
		mobileCifLogin.switchToTheVirtualtourFrame();
		otherPage.verifyWelcomeStonybrookHeader();
		cifLogin.verifyAreYouLabel();
		cifLogin.clickProspectiveStudentButton();
		ExtentTestManager.getTest().pass("prospective_student is clicked");
		otherPage.verifyWhatDescribeYouText();
		ExtentTestManager.getTest().pass("\"What Best Describes You?\" - text displayed on the ProspectiveStudentOptions Page");
		mobileProspectiveStudentPage.clickProspectiveStudentHighSchoolStudentButton();
		ExtentTestManager.getTest().pass("ProspectiveStudentHighSchoolStudentButton is clicked");
		mobileCifLogin.verifyHighSchoolGraduationYearLabel();
		ExtentTestManager.getTest().pass("HighSchoolGraduationYearLabel is verified");
		mobileCifLogin.verifyIntendedEnrollmentTearAndTermLabel();
		ExtentTestManager.getTest().pass("IntendedEnrollmentTearAndTermLabel is verified");
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Next Button is clicked");
		mobileCifLogin.verifyYourEmailPlaceholderTextbox();
		ExtentTestManager.getTest().pass("YourEmailPlaceholderTextbox is verified");
		mobileCifLogin.verifyFirstnamePlaceholderTextbox();
		ExtentTestManager.getTest().pass("FirstnamePlaceholderTextbox is verified");
		mobileCifLogin.verifyLastnamePlaceholderTextbox();
		ExtentTestManager.getTest().pass("LastnamePlaceholderTextbox is verified");
		mobileCifLogin.verifyYourEmailLabel();
		ExtentTestManager.getTest().pass("YourEmailLabel is verified");
		mobileCifLogin.verifyFirstNameLabel();
		ExtentTestManager.getTest().pass("FirstNameLabel is verified");
		mobileCifLogin.verifyLastNameLabel();
		ExtentTestManager.getTest().pass("LastNameLabel is verified");
		otherPage.enterEmail(setData.get("EmailID"));
		ExtentTestManager.getTest().pass("Enter the email");
		otherPage.enterFirstName(setData.get("FirstName"));
		ExtentTestManager.getTest().pass("Enter the firstname");
		otherPage.enterLastName(setData.get("LastName"));
		ExtentTestManager.getTest().pass("Enter the lastname");
		mobileCifLogin.enterDOB(setData.get("DoB"));
		ExtentTestManager.getTest().pass("Enter the dob");
		otherPage.clickNextButton();
		mobileCifLogin.verifyWhereAreYouFromLabel();
		ExtentTestManager.getTest().pass("WhereAreYouFromLabel is verified in postal code page");
		mobileCifLogin.enterPostalCode(setData.get("PostalCode"));
		otherPage.clickNextButton();
		mobileProspectiveStudentPage.enterCurrentHighSchoolName();
		otherPage.clickNextButton();
		mobileProspectiveStudentPage.clickIntendedMajorDropdown();
		mobileCifLogin.enterIntendedMajorDropdown();
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Click on next button");
		mobileCifLogin.enterInvalidSatScoreAndVerifyTheErrorMessage();
		ExtentTestManager.getTest().pass("Enter Invalid Sat Score And Verified The Error Message");
		mobileRegistrationLegacyFormPage.selectSATScore();
		mobileCifLogin.enterInvalidActScoreAndVerifyTheErrorMessage();
		ExtentTestManager.getTest().pass("Enter Invalid ACT Score And Verified The Error Message");
		mobileCifLogin.enterActScoreTextbox();
		mobileCifLogin.enterInvalidGpacoreAndVerifyTheErrorMessage();
		ExtentTestManager.getTest().pass("Enter Invalid GPA Score And Verified The Error Message");
		mobileCifLogin.enterGpaScoreTextbox();
		otherPage.clickNextButton();
		ExtentTestManager.getTest().pass("Click on next button");
		mobileCifLogin.enterPhoneNumber(setData.get("PhoneNo"));
		mobileParentAndGuardianPage.enterPhoneNumber(setData.get("PhoneNo"));
		mobileRegistrationLegacyFormPage.selectGenderDropdownOptionDynamic();
		ExtentTestManager.getTest().pass("Gender is selected");
		mobileCifLogin.clickAcknowledgementCheckbox();
		ExtentTestManager.getTest().pass("Acknowledgement Checkbox is clicked");
		otherPage.clickDoneButton();
		ExtentTestManager.getTest().pass("Click on done button");
		otherPage.verifyGetReadyMessage();
		ExtentTestManager.getTest().pass("Get ready message is verified");
	}
}